apiVersion: v1
kind: Service
metadata:
  name: ethereum-bootnode
spec:
  selector:
    app: ethereum-bootnode
  ports:
  - name: discovery
    port: 30301
    protocol: UDP
  - name: http
    port: 80
