apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: ethereum-miner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ethereum-miner
  template:
    metadata:
      labels:
        app: ethereum-miner
    spec:
      containers:
      - name: ethereum-miner
        image: ethereum/client-go:v1.7.3
        command: ["/bin/sh"]
        args:
        - "-c"
        - "geth --bootnodes=`cat /root/.ethereum/bootnodes` --mine --etherbase=908012cc39a931b7eace6352e5ec9735f2624603 --unlock=908012cc39a931b7eace6352e5ec9735f2624603 --password=/etc/account-password/password --networkid=5 --targetgaslimit=4294967295"
        ports:
        - name: discovery-udp
          containerPort: 30303
          protocol: UDP
        - name: discovery-tcp
          containerPort: 30303
        volumeMounts:
        - name: data
          mountPath: /root/.ethereum
        - name: account-password
          mountPath: /etc/account-password
      initContainers:
      - name: init-genesis
        image: ethereum/client-go:v1.7.3
        args:
        - "init"
        - "/var/geth/genesis.json"
        volumeMounts:
        - name: data
          mountPath: /root/.ethereum
        - name: config
          mountPath: /var/geth
      - name: setup-account
        image: ethereum/client-go:v1.7.3
        command: ["/bin/sh"]
        args:
        - "-c"
        - "cp /etc/account-key/key /root/.ethereum/keystore/miner-account"
        volumeMounts:
        - name: data
          mountPath: /root/.ethereum
        - name: account-key
          mountPath: /etc/account-key
      - name: get-bootnodes
        image: ethereum/client-go:v1.7.3
        command: ["/bin/sh"]
        args:
        - "-c"
        - |-
          while ! nc -z -w 2 ethereum-bootnode 80; do echo 'Waiting for bootnode service...'; sleep 5; done
          while [ -z "$(nc -w 2 ethereum-bootnode 80)" ]; do echo 'Waiting for bootnode address...'; sleep 5; done
          nc ethereum-bootnode 80 | tee /geth/bootnodes
        volumeMounts:
        - name: data
          mountPath: /geth
      volumes:
      - name: data
        emptyDir: {}
      - name: config
        configMap:
          name: ethereum-config
      - name: account-key
        configMap:
          name: miner-account
      - name: account-password
        secret:
          secretName: miner-account-password
